### ISSUE TITLE
SA step has no result for this input data

### ISSUE THREAD

**Issue by gregory-naonedit** [thelia-modules/Chronopost#8]
Certaines générations d'étiquette sont KO.
Le fichier de trace `public_html/log/log-chronopost.txt` est vide
J'ai trouvé la trace de l'erreur dans le fichier `public_html/log/log-thelia.txt`
`1: ERROR [SetDeliveryType.php:createChronopostLabel()] {440} 2020-05-25 15:09:06:#CHRONOPOST // Error when trying to create the label. Chronopost response : SA step has no result for this input data`

Peut être est-ce lié, certaines valeurs `Delivery Type` et `Code` sont vides
![issue-chronopost_delivery-type](https://user-images.githubusercontent.com/65647099/82819561-db55a300-9ea0-11ea-8ef7-abdba68bf4ff.JPG)

Merci

**Comment by LMCreation** [comment]
I have the same probleme , do you find a solution ?

**Comment by SarobidyS** [comment]
It's the RecipientZip code who doenst match the recipientCountry, for me it was that!

**Comment by amine-y** [comment]
Two years and still no response
